@extends('layouts.frontend.app')
@section('content')
<section class="banner-area">
    <div class="banner-content-area">
        <h2>Terms And Conditions</h2>
    </div>
</section>
<section class="main-section">
    <div class="container">
        <p>Ut dolor in est laboris in est voluptate aliqua consequat excepteur aute ut sed quis mollit cillum sunt ullamco ut eiusmod reprehenderit magna dolor anim nulla duis occaecat consectetur pariatur aliquip consectetur fugiat magna dolor nisi eiusmod dolor in cupidatat dolore cillum ut dolore eu laborum incididunt aliqua mollit mollit pariatur cupidatat eu non id ea occaecat excepteur quis ullamco quis qui labore pariatur qui dolor aliquip sunt id do dolor dolor officia eiusmod deserunt sed commodo cillum cupidatat qui labore eiusmod elit nostrud irure nulla ex tempor adipisicing quis elit sint dolore id ullamco cillum ut incididunt minim aute elit mollit eu nostrud proident incididunt eu cillum culpa culpa irure sit est sint anim non nostrud cillum sed fugiat consequat amet pariatur ad officia id adipisicing aute sint ut anim occaecat occaecat dolore irure reprehenderit mollit occaecat ex sit do irure sit sed laboris voluptate in elit laborum nisi commodo commodo in ut dolor velit quis.</p>
        <p>Ut dolor in est laboris in est voluptate aliqua consequat excepteur aute ut sed quis mollit cillum sunt ullamco ut eiusmod reprehenderit magna dolor anim nulla duis occaecat consectetur pariatur aliquip consectetur fugiat magna dolor nisi eiusmod dolor in cupidatat dolore cillum ut dolore eu laborum incididunt aliqua mollit mollit pariatur cupidatat eu non id ea occaecat excepteur quis ullamco quis qui labore pariatur qui dolor aliquip sunt id do dolor dolor officia eiusmod deserunt sed commodo cillum cupidatat qui labore eiusmod elit nostrud irure nulla ex tempor adipisicing quis elit sint dolore id ullamco cillum ut incididunt minim aute elit mollit eu nostrud proident incididunt eu cillum culpa culpa irure sit est sint anim non nostrud cillum sed fugiat consequat amet pariatur ad officia id adipisicing aute sint ut anim occaecat occaecat dolore irure reprehenderit mollit occaecat ex sit do irure sit sed laboris voluptate in elit laborum nisi commodo commodo in ut dolor velit quis.</p>
        <p>Ut dolor in est laboris in est voluptate aliqua consequat excepteur aute ut sed quis mollit cillum sunt ullamco ut eiusmod reprehenderit magna dolor anim nulla duis occaecat consectetur pariatur aliquip consectetur fugiat magna dolor nisi eiusmod dolor in cupidatat dolore cillum ut dolore eu laborum incididunt aliqua mollit mollit pariatur cupidatat eu non id ea occaecat excepteur quis ullamco quis qui labore pariatur qui dolor aliquip sunt id do dolor dolor officia eiusmod deserunt sed commodo cillum cupidatat qui labore eiusmod elit nostrud irure nulla ex tempor adipisicing quis elit sint dolore id ullamco cillum ut incididunt minim aute elit mollit eu nostrud proident incididunt eu cillum culpa culpa irure sit est sint anim non nostrud cillum sed fugiat consequat amet pariatur ad officia id adipisicing aute sint ut anim occaecat occaecat dolore irure reprehenderit mollit occaecat ex sit do irure sit sed laboris voluptate in elit laborum nisi commodo commodo in ut dolor velit quis.</p>
        <p>Ut dolor in est laboris in est voluptate aliqua consequat excepteur aute ut sed quis mollit cillum sunt ullamco ut eiusmod reprehenderit magna dolor anim nulla duis occaecat consectetur pariatur aliquip consectetur fugiat magna dolor nisi eiusmod dolor in cupidatat dolore cillum ut dolore eu laborum incididunt aliqua mollit mollit pariatur cupidatat eu non id ea occaecat excepteur quis ullamco quis qui labore pariatur qui dolor aliquip sunt id do dolor dolor officia eiusmod deserunt sed commodo cillum cupidatat qui labore eiusmod elit nostrud irure nulla ex tempor adipisicing quis elit sint dolore id ullamco cillum ut incididunt minim aute elit mollit eu nostrud proident incididunt eu cillum culpa culpa irure sit est sint anim non nostrud cillum sed fugiat consequat amet pariatur ad officia id adipisicing aute sint ut anim occaecat occaecat dolore irure reprehenderit mollit occaecat ex sit do irure sit sed laboris voluptate in elit laborum nisi commodo commodo in ut dolor velit quis.</p>
    </div>
</section>
@endsection
